import {scale} from '../utils/screenUtility';
export const LoginJSON = {
  title: '',
  logo: true,
  fields: [
    {
      id: 1,
      name: 'username',
      label: 'User Name / ID',
      type: 'text',
      placeholder: 'Enter User Name / ID',
      multiline: false,
      required: true,
      secureTextEntry: false,
      style: {
        backgroundColor: 'white',
        borderColor: '#C3D0DE',
        borderWidth: 1,
        borderRadius: 5,
        padding: scale(10),
        height: scale(40),
        fontSize: scale(14),
        fontFamily: 'SourceSansPro-Regular',
        color: '#4D4F5C',
      },
    },
    {
      id: 2,
      name: 'password',
      label: 'Password',
      type: 'password',
      placeholder: 'Enter Password',
      secureTextEntry: true,
      required: true,
      style: {
        backgroundColor: 'white',
        borderColor: '#C3D0DE',
        borderWidth: 1,
        borderRadius: 5,
        padding: 10,
        height: scale(40),
        flex: 1,
        marginTop: scale(5),
        fontSize: scale(14),
        fontFamily: 'SourceSansPro-Regular',
        color: '#4D4F5C',
      },
    },

    {
      id: 3,
      type: 'button',
      text: 'Submit',
      name: 'Submit',
      required: false,
      label: 'LOGIN',
      navigation: () => {},
      nextApi: '',
      style: {
        backgroundColor: '#349beb',
        height: scale(40),
        borderRadius: 4,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: scale(20),
      },
    },
    {
      id: 4,
      type: 'link',
      label: 'Forgot User Name / ID ?',
      navigation: () => {},
      style: {},
      required: false,
    },
    {
      id: 5,
      type: 'link',
      label: 'Forgot Password ?',
      navigation: () => {},
      style: {},
      required: false,
    },
  ],
};
