import {scale} from '../utils/screenUtility';
export const PersonalDetailsJSON = {
  title: 'Personal Details',
  fields: [
    {
      name: 'Personal Info',
      expanded: true,
      contents: [
        {
          id: 1,
          view: 'multi',
          type: 'multi',
          content: [
            {
              id: 11,
              name: 'title',
              label: 'Title',
              title: 'title',
              type: 'dropdown',
              required: true,
              placeholder: 'Select',
              data: [
                {
                  id: 1,
                  value: 'Mr.',
                  label: 'Mr.',
                },
                {
                  id: 2,
                  value: 'Mrs.',
                  label: 'Mrs.',
                },
                {
                  id: 3,
                  value: 'Ms',
                  label: 'Ms',
                },
                {
                  id: 4,
                  value: 'Others',
                  label: 'Others',
                },
              ],
            },
            {
              id: 12,
              name: 'firstName',
              label: 'First Name',
              type: 'text',
              placeholder: 'Enter First Name',
              secureTextEntry: false,
              required: true,
              // value: 'satya',
              style: {
                backgroundColor: 'white',
                borderColor: '#C3D0DE',
                borderWidth: 1,
                borderRadius: 5,
                padding: 10,
                marginBottom: 10,
                height: scale(40),
              },
            },
          ],
        },
        {
          id: 2,
          view: 'multi',
          type: 'multi',
          content: [
            {
              id: 13,
              view: 'single',
              name: 'middleName',
              label: 'Middle Name',
              type: 'text',
              placeholder: 'Enter Middle Name',
              secureTextEntry: false,
              required: false,
              style: {
                backgroundColor: 'white',
                borderColor: '#C3D0DE',
                borderWidth: 1,
                borderRadius: 5,
                padding: 10,
                marginBottom: 10,
              },
            },
            {
              id: 14,
              view: 'single',
              name: 'lastName',
              label: 'Last Name',
              type: 'text',
              placeholder: 'Enter Last Name',
              secureTextEntry: false,
              required: true,
              style: {
                backgroundColor: 'white',
                borderColor: '#C3D0DE',
                borderWidth: 1,
                borderRadius: 5,
                padding: 10,
                marginBottom: 10,
              },
            },
          ],
        },
        {
          id: 4,
          view: 'single',
          name: 'email',
          label: 'Email',
          type: 'email',
          placeholder: 'Enter email',
          value: '',
          secureTextEntry: false,
          required: true,
          style: {
            backgroundColor: 'white',
            borderColor: '#C3D0DE',
            borderWidth: 1,
            borderRadius: 5,
            padding: 10,
            marginBottom: 10,
          },
        },
      ],
    },
    {
      name: 'Marital Status',
      expanded: false,

      contents: [
        {
          id: 1,
          view: 'multi',
          type: 'multi',
          content: [
            {
              id: 11,
              name: 'title',
              label: 'Title',
              title: 'title',
              type: 'dropdown',
              required: true,
              placeholder: 'Select',
              data: [
                {
                  id: 1,
                  value: 'Mr.',
                  label: 'Mr.',
                },
                {
                  id: 2,
                  value: 'Mrs.',
                  label: 'Mrs.',
                },
                {
                  id: 3,
                  value: 'Ms',
                  label: 'Ms',
                },
                {
                  id: 4,
                  value: 'Others',
                  label: 'Others',
                },
              ],
            },
            {
              id: 12,
              name: 'firstName',
              label: 'First Name',
              type: 'text',
              placeholder: 'Enter First Name',
              secureTextEntry: false,
              required: true,
              style: {
                backgroundColor: 'white',
                borderColor: '#C3D0DE',
                borderWidth: 1,
                borderRadius: 5,
                padding: 10,
                marginBottom: 10,
                height: scale(40),
              },
            },
          ],
        },
      ],
    },
    {
      name: 'Current Address Details',
      expanded: false,

      contents: [
        {
          id: 1,
          view: 'multi',
          type: 'multi',
          content: [
            {
              id: 11,
              name: 'title',
              label: 'Title',
              title: 'title',
              type: 'dropdown',
              required: true,
              placeholder: 'Select',
              data: [
                {
                  id: 1,
                  value: 'Mr.',
                  label: 'Mr.',
                },
                {
                  id: 2,
                  value: 'Mrs.',
                  label: 'Mrs.',
                },
                {
                  id: 3,
                  value: 'Ms',
                  label: 'Ms',
                },
                {
                  id: 4,
                  value: 'Others',
                  label: 'Others',
                },
              ],
            },
            {
              id: 12,
              name: 'firstName',
              label: 'First Name',
              type: 'text',
              placeholder: 'Enter First Name',
              secureTextEntry: false,
              required: true,
              style: {
                backgroundColor: 'white',
                borderColor: '#C3D0DE',
                borderWidth: 1,
                borderRadius: 5,
                padding: 10,
                marginBottom: 10,
                height: scale(40),
              },
            },
          ],
        },
      ],
    },
    {
      name: 'Permanent Address Details',
      expanded: false,

      contents: [
        {
          id: 1,
          view: 'multi',
          type: 'multi',
          content: [
            {
              id: 11,
              name: 'title',
              label: 'Title',
              title: 'title',
              type: 'dropdown',
              required: true,
              placeholder: 'Select',
              data: [
                {
                  id: 1,
                  value: 'Mr.',
                  label: 'Mr.',
                },
                {
                  id: 2,
                  value: 'Mrs.',
                  label: 'Mrs.',
                },
                {
                  id: 3,
                  value: 'Ms',
                  label: 'Ms',
                },
                {
                  id: 4,
                  value: 'Others',
                  label: 'Others',
                },
              ],
            },
            {
              id: 12,
              name: 'firstName',
              label: 'First Name',
              type: 'text',
              placeholder: 'Enter First Name',
              secureTextEntry: false,
              required: true,
              style: {
                backgroundColor: 'white',
                borderColor: '#C3D0DE',
                borderWidth: 1,
                borderRadius: 5,
                padding: 10,
                marginBottom: 10,
                height: scale(40),
              },
            },
          ],
        },
      ],
    },
    {
      name: 'Foreign Address Details',
      expanded: false,

      contents: [
        {
          id: 1,
          view: 'multi',
          type: 'multi',
          content: [
            {
              id: 11,
              name: 'title',
              label: 'Title',
              title: 'title',
              type: 'dropdown',
              required: true,
              placeholder: 'Select',
              data: [
                {
                  id: 1,
                  value: 'Mr.',
                  label: 'Mr.',
                },
                {
                  id: 2,
                  value: 'Mrs.',
                  label: 'Mrs.',
                },
                {
                  id: 3,
                  value: 'Ms',
                  label: 'Ms',
                },
                {
                  id: 4,
                  value: 'Others',
                  label: 'Others',
                },
              ],
            },
            {
              id: 12,
              name: 'firstName',
              label: 'First Name',
              type: 'text',
              placeholder: 'Enter First Name',
              secureTextEntry: false,
              required: true,
              style: {
                backgroundColor: 'white',
                borderColor: '#C3D0DE',
                borderWidth: 1,
                borderRadius: 5,
                padding: 10,
                marginBottom: 10,
                height: scale(40),
              },
            },
          ],
        },
      ],
    },
    {
      name: 'Place of Birth',
      expanded: false,

      contents: [
        {
          id: 1,
          view: 'multi',
          type: 'multi',
          content: [
            {
              id: 11,
              name: 'title',
              label: 'Title',
              title: 'title',
              type: 'dropdown',
              required: true,
              placeholder: 'Select',
              data: [
                {
                  id: 1,
                  value: 'Mr.',
                  label: 'Mr.',
                },
                {
                  id: 2,
                  value: 'Mrs.',
                  label: 'Mrs.',
                },
                {
                  id: 3,
                  value: 'Ms',
                  label: 'Ms',
                },
                {
                  id: 4,
                  value: 'Others',
                  label: 'Others',
                },
              ],
            },
            {
              id: 12,
              name: 'firstName',
              label: 'First Name',
              type: 'text',
              placeholder: 'Enter First Name',
              secureTextEntry: false,
              required: true,
              style: {
                backgroundColor: 'white',
                borderColor: '#C3D0DE',
                borderWidth: 1,
                borderRadius: 5,
                padding: 10,
                marginBottom: 10,
                height: scale(40),
              },
            },
          ],
        },
      ],
    },
    {
      name: 'Biographic Information',
      expanded: false,

      contents: [
        {
          id: 1,
          view: 'multi',
          type: 'multi',
          content: [
            {
              id: 11,
              name: 'title',
              label: 'Title',
              title: 'title',
              type: 'dropdown',
              required: true,
              placeholder: 'Select',
              value: '',
              data: [
                {
                  id: 1,
                  value: 'Mr.',
                  label: 'Mr.',
                },
                {
                  id: 2,
                  value: 'Mrs.',
                  label: 'Mrs.',
                },
                {
                  id: 3,
                  value: 'Ms',
                  label: 'Ms',
                },
                {
                  id: 4,
                  value: 'Others',
                  label: 'Others',
                },
              ],
            },
            {
              id: 12,
              name: 'firstName',
              label: 'First Name',
              type: 'text',
              placeholder: 'Enter First Name',
              secureTextEntry: false,
              required: true,
              value: '',
              style: {
                backgroundColor: 'white',
                borderColor: '#C3D0DE',
                borderWidth: 1,
                borderRadius: 5,
                padding: 10,
                marginBottom: 10,
                height: scale(40),
              },
            },
          ],
        },
      ],
    },
    {
      name: 'Passport Details',
      expanded: false,
      contents: [
        {
          id: 11,
          view: 'single',
          type: 'text',
          name: 'Passport Number',
          label: 'Passport Number',
          title: 'Passport Number',
          required: true,
          placeholder: 'Enter Passport Number',
          value: 'asas',
          style: {
            backgroundColor: 'white',
            borderColor: '#C3D0DE',
            borderWidth: 1,
            borderRadius: 5,
            padding: 10,
            marginBottom: 10,
            height: scale(40),
          },
        },
        {
          id: 12,
          view: 'single',
          type: 'text',
          name: 'Issuing Authority',
          label: 'Issuing Authority',
          title: 'Issuing Authority',
          required: true,
          placeholder: 'Enter Issuing Authority',
          value: '',
          style: {
            backgroundColor: 'white',
            borderColor: '#C3D0DE',
            borderWidth: 1,
            borderRadius: 5,
            padding: 10,
            marginBottom: 10,
            height: scale(40),
          },
        },
        {
          id: 13,
          view: 'single',
          type: 'text',
          name: 'Date of Issue',
          label: 'Date of Issue',
          title: 'Date of Issue',
          required: true,
          placeholder: 'Enter Date of Issue',
          value: '',
          style: {
            backgroundColor: 'white',
            borderColor: '#C3D0DE',
            borderWidth: 1,
            borderRadius: 5,
            padding: 10,
            marginBottom: 10,
            height: scale(40),
          },
        },
        {
          id: 14,
          view: 'single',
          type: 'text',
          name: 'Date of Expiry',
          label: 'Date of Expiry',
          title: 'Date of Expiry',
          required: true,
          placeholder: 'Enter Date of Expiry',
          value: '',
          style: {
            backgroundColor: 'white',
            borderColor: '#C3D0DE',
            borderWidth: 1,
            borderRadius: 5,
            padding: 10,
            marginBottom: 10,
            height: scale(40),
          },
        },
        {
          id: 15,
          view: 'single',
          type: 'button',
          name: 'Add the Photocopy of your passport',
          label: 'Add the Photocopy of your passport',
          title: 'Add the Photocopy of your passport',
          required: false,
          placeholder: 'Enter Add the Photocopy of your passport',
          value: '',
        },
      ],
    },
  ],
};
