import {scale} from '../utils/screenUtility';
export const RegistrationJSON = {
  title: '',
  logo: true,
  fields: [
    {
      id: 1,
      view: 'multi',
      type: 'multi',
      content: [
        {
          id: 11,
          name: 'title',
          label: 'Title',
          title: 'title',
          type: 'dropdown',
          required: true,
          placeholder: 'Select',
          data: [
            {
              id: 1,
              value: 'Mr.',
              label: 'Mr.',
            },
            {
              id: 2,
              value: 'Mrs.',
              label: 'Mrs.',
            },
            {
              id: 3,
              value: 'Ms',
              label: 'Ms',
            },
            {
              id: 4,
              value: 'Others',
              label: 'Others',
            },
          ],
        },
        {
          id: 12,
          name: 'firstName',
          label: 'First Name',
          type: 'text',
          placeholder: 'Enter First Name',
          secureTextEntry: false,
          required: true,
          style: {
            backgroundColor: 'white',
            borderColor: '#C3D0DE',
            borderWidth: 1,
            borderRadius: 5,
            padding: 10,
            marginBottom: 10,
            height: scale(40),
          },
        },
      ],
    },
    {
      id: 2,
      view: 'multi',
      type: 'multi',
      content: [
        {
          id: 13,
          view: 'single',
          name: 'middleName',
          label: 'Middle Name',
          type: 'text',
          placeholder: 'Enter Middle Name',
          secureTextEntry: false,
          required: true,
          style: {
            backgroundColor: 'white',
            borderColor: '#C3D0DE',
            borderWidth: 1,
            borderRadius: 5,
            padding: 10,
            marginBottom: 10,
          },
        },
        {
          id: 14,
          view: 'single',
          name: 'lastName',
          label: 'Last Name',
          type: 'text',
          placeholder: 'Enter Last Name',
          secureTextEntry: false,
          required: true,
          style: {
            backgroundColor: 'white',
            borderColor: '#C3D0DE',
            borderWidth: 1,
            borderRadius: 5,
            padding: 10,
            marginBottom: 10,
          },
        },
      ],
    },
    {
      id: 3,
      view: 'single',
      name: 'PhoneNumber',
      countryName: 'countryName',
      type: 'phoneInput',
      label: 'Phone Number',
      required: true,
    },
    {
      id: 4,
      view: 'single',
      name: 'email',
      label: 'Email',
      type: 'email',
      placeholder: 'Enter email',
      secureTextEntry: false,
      required: true,
      style: {
        backgroundColor: 'white',
        borderColor: '#C3D0DE',
        borderWidth: 1,
        borderRadius: 5,
        padding: 10,
        marginBottom: 10,
      },
    },
    {
      id: 5,
      view: 'single',
      name: 'userId',
      label: 'User Name / ID',
      type: 'text',
      placeholder: 'Enter User Name / Id',
      secureTextEntry: false,
      required: true,
      style: {
        backgroundColor: 'white',
        borderColor: '#C3D0DE',
        borderWidth: 1,
        borderRadius: 5,
        padding: 10,
        marginBottom: 10,
      },
    },
    {
      id: 6,
      view: 'multi',
      type: 'multi',
      content: [
        {
          id: 15,
          name: 'password',
          label: 'Password',
          type: 'password',
          placeholder: 'Enter your password',
          secureTextEntry: true,
          required: true,
          style: {
            backgroundColor: 'white',
            borderColor: '#C3D0DE',
            borderWidth: 1,
            borderRadius: 5,
            padding: 10,
            marginBottom: 10,
          },
        },
        {
          id: 16,
          name: 'confirmpassword',
          label: 'Confirm Password',
          type: 'password',
          placeholder: 'Enter confirm password',
          secureTextEntry: true,
          required: true,
          style: {
            backgroundColor: 'white',
            borderColor: '#C3D0DE',
            borderWidth: 1,
            borderRadius: 5,
            padding: 10,
            marginBottom: 10,
          },
        },
      ],
    },
  ],
};
